package com.kgsoft.favorsbank.ui

/** UI string translations for the 8 new languages. Missing keys fall back to Arabic/English. */
object LangTables {
    private val table: Map<String, Map<String, String>> = mapOf(
        "fr" to mapOf(
            "appName" to "Banque des Hasanat",
            "hasanatSuffix" to "hassanat",
            "loginTitle" to "Connexion",
            "loginSubtitle" to "Une étape inutile que vous pouvez ignorer",
            "username" to "Nom d'utilisateur",
            "password" to "Mot de passe",
            "login" to "Se connecter",
            "dontShowAgain" to "Ne plus afficher",
            "skip" to "Ignorer",
            "tasks" to "Tâches",
            "business" to "Actions",
            "dailyReview" to "Bilan quotidien",
            "myAccount" to "Mon compte",
            "share" to "Partager",
            "salatTimes" to "Horaires de prière",
            "azkar" to "Adhkar du matin et du soir",
            "sibha" to "Tasbih",
            "settings" to "Paramètres",
            "about" to "À propos",
            "language" to "Langue",
            "exit" to "Quitter",
            "suggestedBusiness" to "Bonnes actions suggérées",
            "investmentDuration" to "Durée",
            "netProfit" to "Récompense",
            "investmentDetails" to "Détails :",
            "confirmCompletion" to "Confirmer l'accomplissement",
            "useSibha" to "Utiliser le tasbih",
            "didYouDoIt" to "L'avez-vous accompli ?",
            "confirmHonestly" to "Confirmez-vous honnêtement avoir accompli la tâche mentionnée ici ?",
            "yesOfCourse" to "Oui, bien sûr",
            "noLater" to "Non, je le ferai",
            "blessedMsg" to "Qu'Allah vous bénisse, nouvel accomplissement : ",
            "prev" to "Précédent",
            "next" to "Suivant",
            "endOfQuestions" to "Questions terminées !",
            "startOfQuestions" to "Début des questions !",
            "reset" to "Réinitialiser",
            "customWird" to "Wird personnalisé",
            "wirdText" to "Texte du wird",
            "repeatCount" to "Nombre de répétitions",
            "save" to "Enregistrer",
            "cancel" to "Annuler",
            "dontLeaveEmpty" to "Ne laissez pas ce champ vide",
            "numbersOnly" to "Chiffres uniquement",
            "notifications" to "Notifications",
            "nightTheme" to "Mode nuit",
            "zikrToasts" to "Rappels d'adhkar",
            "toastTasbih" to "Rappels de tasbih et d'adhkar",
            "toastProphet" to "Rappels de salawat",
            "toastAll" to "Tout",
            "reportBug" to "Signaler un bug",
            "enabled" to "Activé",
            "disabled" to "Désactivé",
            "chooseLanguage" to "Choisir la langue de l'application",
            "saveChanges" to "Enregistrer les modifications ?",
            "restartNeeded" to "Vous devez redémarrer l'application pour voir les changements.",
            "restart" to "Redémarrer",
            "later" to "Plus tard",
            "langChanged" to "Langue modifiée avec succès, redémarrez l'application pour voir les changements",
            "accountDetails" to "Détails du compte",
            "level" to "Niveau",
            "editAccount" to "Modifier le compte",
            "balance" to "Solde",
            "aboutApp" to "À propos de l'application",
            "policy" to "Politique",
            "donate" to "Faire un don",
            "understood" to "Compris",
            "close" to "Fermer",
            "shareAndEarn" to "Partager et gagner des récompenses",
            "checkUpdates" to "Vérifier les mises à jour",
            "sendSuggestion" to "Envoyer une suggestion",
            "reportBugTitle" to "Signaler un bug.",
            "writeHere" to "Écrivez ici...",
            "submit" to "Envoyer",
            "fajr" to "Fajr",
            "shuruj" to "Chourouk",
            "dhuhr" to "Dhuhr",
            "asr" to "Asr",
            "maghrib" to "Maghrib",
            "isha" to "Isha",
            "nextPrayer" to "Prochaine prière",
            "remainingTime" to "Temps restant",
            "locationTitle" to "Définir la localisation",
            "locationMessage" to "Nous avons besoin de votre localisation une seule fois pour calculer des horaires de prière précis pour votre ville.",
            "useMyLocation" to "Utiliser ma localisation",
            "useKhartoum" to "Khartoum (par défaut)",
            "completedLog" to "Historique des tâches accomplies",
            "noCompletedTasks" to "Aucune tâche accomplie pour le moment",
            "hasanatAdded" to "ajouté à votre solde",
            "blessedWithCount" to "Qu'Allah vous bénisse ! Vous avez gagné",
            "mayAllahAccept" to "Qu'Allah accepte votre adoration",
            "aboutText" to "Banque des Hasanat est une application islamique qui vous aide à investir votre temps dans les bonnes actions : tâches suggérées avec récompenses et preuves, bilan spirituel quotidien, adhkar du matin et du soir, un tasbih numérique et les horaires de prière. Partagez l'application et faites-en une aumône continue.",
        ),
        "ur" to mapOf(
            "appName" to "بینک آف حسنات",
            "hasanatSuffix" to "حسنات",
            "loginTitle" to "لاگ اِن",
            "loginSubtitle" to "ایک غیر ضروری مرحلہ جسے آپ چھوڑ سکتے ہیں",
            "username" to "صارف کا نام",
            "password" to "پاس ورڈ",
            "login" to "داخل ہوں",
            "dontShowAgain" to "دوبارہ نہ دکھائیں",
            "skip" to "چھوڑیں",
            "tasks" to "کام",
            "business" to "اعمال",
            "dailyReview" to "روزانہ محاسبہ",
            "myAccount" to "میرا اکاؤنٹ",
            "share" to "شیئر کریں",
            "salatTimes" to "نماز کے اوقات",
            "azkar" to "صبح و شام کے اذکار",
            "sibha" to "تسبیح",
            "settings" to "ترتیبات",
            "about" to "ایپ کے بارے میں",
            "language" to "زبان",
            "exit" to "خروج",
            "suggestedBusiness" to "تجویز کردہ اعمال",
            "investmentDuration" to "مدت",
            "netProfit" to "ثواب",
            "investmentDetails" to "تفصیلات:",
            "confirmCompletion" to "تکمیل کی تصدیق",
            "useSibha" to "تسبیح استعمال کریں",
            "didYouDoIt" to "کیا آپ نے یہ کام کر لیا؟",
            "confirmHonestly" to "کیا آپ سچے دل سے تصدیق کرتے ہیں کہ آپ نے یہاں مذکور کام مکمل کر لیا ہے؟",
            "yesOfCourse" to "جی ہاں، بالکل",
            "noLater" to "نہیں، میں کروں گا",
            "blessedMsg" to "اللہ آپ کو برکت دے، نئی کامیابی: ",
            "prev" to "پچھلا",
            "next" to "اگلا",
            "endOfQuestions" to "سوالات ختم!",
            "startOfQuestions" to "سوالات کا آغاز!",
            "reset" to "صفر کریں",
            "customWird" to "ذاتی ورد",
            "wirdText" to "ورد کا متن",
            "repeatCount" to "تکرار کی تعداد",
            "save" to "محفوظ کریں",
            "cancel" to "منسوخ کریں",
            "dontLeaveEmpty" to "اس خانے کو خالی نہ چھوڑیں",
            "numbersOnly" to "صرف اعداد درج کریں",
            "notifications" to "اطلاعات",
            "nightTheme" to "نائٹ موڈ",
            "zikrToasts" to "اذکار کی یاد دہانی",
            "toastTasbih" to "تسبیح و اذکار کی یاد دہانی",
            "toastProphet" to "نبی ﷺ پر درود",
            "toastAll" to "سب",
            "reportBug" to "خرابی کی اطلاع دیں",
            "enabled" to "فعال",
            "disabled" to "غیر فعال",
            "chooseLanguage" to "ایپ کی زبان منتخب کریں",
            "saveChanges" to "تبدیلیاں محفوظ کریں؟",
            "restartNeeded" to "تبدیلیاں دیکھنے کے لیے ایپ دوبارہ شروع کریں۔",
            "restart" to "دوبارہ شروع کریں",
            "later" to "بعد میں",
            "langChanged" to "زبان کامیابی سے تبدیل ہو گئی، تبدیلیاں دیکھنے کے لیے ایپ دوبارہ شروع کریں",
            "accountDetails" to "اکاؤنٹ کی تفصیلات",
            "level" to "درجہ",
            "editAccount" to "اکاؤنٹ میں ترمیم",
            "balance" to "بیلنس",
            "aboutApp" to "ایپ کے بارے میں",
            "policy" to "پالیسی",
            "donate" to "عطیہ دیں",
            "understood" to "سمجھ گیا",
            "close" to "بند کریں",
            "shareAndEarn" to "شیئر کریں اور ثواب کمائیں",
            "checkUpdates" to "اپ ڈیٹس چیک کریں",
            "sendSuggestion" to "تجویز بھیجیں",
            "reportBugTitle" to "خرابی کی اطلاع دیں۔",
            "writeHere" to "یہاں لکھیں...",
            "submit" to "بھیجیں",
            "fajr" to "فجر",
            "shuruj" to "طلوع آفتاب",
            "dhuhr" to "ظہر",
            "asr" to "عصر",
            "maghrib" to "مغرب",
            "isha" to "عشاء",
            "nextPrayer" to "اگلی نماز",
            "remainingTime" to "باقی وقت",
            "locationTitle" to "مقام منتخب کریں",
            "locationMessage" to "آپ کے شہر کے لیے نماز کے درست اوقات کے حساب کے لیے ہمیں صرف ایک بار آپ کے مقام کی ضرورت ہے۔",
            "useMyLocation" to "میرا مقام استعمال کریں",
            "useKhartoum" to "خرطوم (پہلے سے منتخب)",
            "completedLog" to "مکمل شدہ کاموں کا ریکارڈ",
            "noCompletedTasks" to "ابھی تک کوئی کام مکمل نہیں ہوا",
            "hasanatAdded" to "آپ کے بیلنس میں شامل",
            "blessedWithCount" to "اللہ آپ کو برکت دے! آپ کو ملا",
            "mayAllahAccept" to "اللہ آپ کی عبادت قبول فرمائے",
            "aboutText" to "بینک آف حسنات ایک اسلامی ایپ ہے جو آپ کے وقت کو نیکیوں میں لگانے میں مدد دیتی ہے: ثواب اور دلیل کے ساتھ تجویز کردہ کام، روزانہ محاسبۂ نفس، صبح و شام کے اذکار، ڈیجیٹل تسبیح، اور نماز کے اوقات۔ ایپ شیئر کریں اور اسے اپنے لیے صدقۂ جاریہ بنائیں۔",
        ),
        "id" to mapOf(
            "appName" to "Bank Hasanat",
            "hasanatSuffix" to "hasanat",
            "loginTitle" to "Masuk",
            "loginSubtitle" to "Langkah yang tidak perlu, Anda dapat melewatinya",
            "username" to "Nama pengguna",
            "password" to "Kata sandi",
            "login" to "Masuk",
            "dontShowAgain" to "Jangan tampilkan lagi",
            "skip" to "Lewati",
            "tasks" to "Tugas",
            "business" to "Amalan",
            "dailyReview" to "Muhasabah harian",
            "myAccount" to "Akun saya",
            "share" to "Bagikan",
            "salatTimes" to "Jadwal salat",
            "azkar" to "Zikir pagi dan petang",
            "sibha" to "Tasbih",
            "settings" to "Pengaturan",
            "about" to "Tentang",
            "language" to "Bahasa",
            "exit" to "Keluar",
            "suggestedBusiness" to "Amalan yang disarankan",
            "investmentDuration" to "Durasi",
            "netProfit" to "Pahala",
            "investmentDetails" to "Detail:",
            "confirmCompletion" to "Konfirmasi penyelesaian",
            "useSibha" to "Gunakan tasbih",
            "didYouDoIt" to "Apakah Anda sudah mengerjakannya?",
            "confirmHonestly" to "Apakah Anda dengan jujur mengonfirmasi bahwa Anda telah menyelesaikan tugas yang disebutkan di sini?",
            "yesOfCourse" to "Ya, tentu saja",
            "noLater" to "Belum, saya akan kerjakan",
            "blessedMsg" to "Barakallahu fiik, pencapaian baru: ",
            "prev" to "Sebelumnya",
            "next" to "Berikutnya",
            "endOfQuestions" to "Pertanyaan selesai!",
            "startOfQuestions" to "Awal pertanyaan!",
            "reset" to "Atur ulang",
            "customWird" to "Wird kustom",
            "wirdText" to "Teks wird",
            "repeatCount" to "Jumlah pengulangan",
            "save" to "Simpan",
            "cancel" to "Batal",
            "dontLeaveEmpty" to "Jangan biarkan kolom ini kosong",
            "numbersOnly" to "Masukkan angka saja",
            "notifications" to "Notifikasi",
            "nightTheme" to "Mode malam",
            "zikrToasts" to "Pengingat zikir",
            "toastTasbih" to "Pengingat tasbih & zikir",
            "toastProphet" to "Selawat kepada Nabi",
            "toastAll" to "Semua",
            "reportBug" to "Laporkan bug",
            "enabled" to "Aktif",
            "disabled" to "Nonaktif",
            "chooseLanguage" to "Pilih bahasa aplikasi",
            "saveChanges" to "Simpan perubahan?",
            "restartNeeded" to "Anda perlu memulai ulang aplikasi untuk melihat perubahan.",
            "restart" to "Mulai ulang",
            "later" to "Nanti",
            "langChanged" to "Bahasa berhasil diubah, mulai ulang aplikasi untuk melihat perubahan",
            "accountDetails" to "Detail akun",
            "level" to "Level",
            "editAccount" to "Edit akun",
            "balance" to "Saldo",
            "aboutApp" to "Tentang aplikasi",
            "policy" to "Kebijakan",
            "donate" to "Donasi",
            "understood" to "Mengerti",
            "close" to "Tutup",
            "shareAndEarn" to "Bagikan dan raih pahala",
            "checkUpdates" to "Periksa pembaruan",
            "sendSuggestion" to "Kirim saran",
            "reportBugTitle" to "Laporkan bug.",
            "writeHere" to "Tulis di sini...",
            "submit" to "Kirim",
            "fajr" to "Subuh",
            "shuruj" to "Terbit matahari",
            "dhuhr" to "Zuhur",
            "asr" to "Asar",
            "maghrib" to "Magrib",
            "isha" to "Isya",
            "nextPrayer" to "Salat berikutnya",
            "remainingTime" to "Sisa waktu",
            "locationTitle" to "Tentukan lokasi",
            "locationMessage" to "Kami membutuhkan lokasi Anda sekali saja untuk menghitung jadwal salat yang akurat sesuai kota Anda.",
            "useMyLocation" to "Gunakan lokasi saya",
            "useKhartoum" to "Khartoum (bawaan)",
            "completedLog" to "Riwayat tugas selesai",
            "noCompletedTasks" to "Belum ada tugas yang selesai",
            "hasanatAdded" to "ditambahkan ke saldo Anda",
            "blessedWithCount" to "Barakallahu fiik! Anda mendapatkan",
            "mayAllahAccept" to "Semoga Allah menerima ibadah Anda",
            "aboutText" to "Bank Hasanat adalah aplikasi Islami yang membantu Anda menginvestasikan waktu dalam ketaatan dan mengumpulkan hasanat: tugas dan amalan yang disarankan beserta pahala dan dalilnya, muhasabah harian, zikir pagi dan petang, tasbih digital, dan jadwal salat. Bagikan aplikasi ini dan jadikan sebagai sedekah jariyah dalam timbangan amal Anda.",
        ),
        "fa" to mapOf(
            "appName" to "بانک حسنات",
            "hasanatSuffix" to "حسنه",
            "loginTitle" to "ورود",
            "loginSubtitle" to "مرحله‌ای غیرضروری که می‌توانید رد کنید",
            "username" to "نام کاربری",
            "password" to "رمز عبور",
            "login" to "ورود",
            "dontShowAgain" to "دیگر نمایش نده",
            "skip" to "رد کردن",
            "tasks" to "وظایف",
            "business" to "اعمال",
            "dailyReview" to "محاسبه روزانه",
            "myAccount" to "حساب من",
            "share" to "اشتراک‌گذاری",
            "salatTimes" to "اوقات نماز",
            "azkar" to "اذکار صبح و شام",
            "sibha" to "تسبیح",
            "settings" to "تنظیمات",
            "about" to "درباره",
            "language" to "زبان",
            "exit" to "خروج",
            "suggestedBusiness" to "اعمال پیشنهادی",
            "investmentDuration" to "مدت",
            "netProfit" to "پاداش (اجر)",
            "investmentDetails" to "جزئیات:",
            "confirmCompletion" to "تأیید انجام",
            "useSibha" to "استفاده از تسبیح",
            "didYouDoIt" to "آیا آن را انجام دادید؟",
            "confirmHonestly" to "آیا صادقانه تأیید می‌کنید که وظیفه ذکر شده در اینجا را انجام داده‌اید؟",
            "yesOfCourse" to "بله، حتماً",
            "noLater" to "نه، انجامش می‌دهم",
            "blessedMsg" to "بارک‌الله فیک، موفقیت جدید: ",
            "prev" to "قبلی",
            "next" to "بعدی",
            "endOfQuestions" to "سؤالات تمام شد!",
            "startOfQuestions" to "شروع سؤالات!",
            "reset" to "صفر کردن",
            "customWird" to "ورد سفارشی",
            "wirdText" to "متن ورد",
            "repeatCount" to "تعداد تکرار",
            "save" to "ذخیره",
            "cancel" to "لغو",
            "dontLeaveEmpty" to "این فیلد را خالی نگذارید",
            "numbersOnly" to "فقط عدد وارد کنید",
            "notifications" to "اعلان‌ها",
            "nightTheme" to "حالت شب",
            "zikrToasts" to "یادآوری اذکار",
            "toastTasbih" to "یادآوری تسبیح و اذکار",
            "toastProphet" to "صلوات بر پیامبر",
            "toastAll" to "همه",
            "reportBug" to "گزارش خطا",
            "enabled" to "فعال",
            "disabled" to "غیرفعال",
            "chooseLanguage" to "زبان برنامه را انتخاب کنید",
            "saveChanges" to "تغییرات ذخیره شود؟",
            "restartNeeded" to "برای دیدن تغییرات باید برنامه را دوباره راه‌اندازی کنید.",
            "restart" to "راه‌اندازی مجدد",
            "later" to "بعداً",
            "langChanged" to "زبان با موفقیت تغییر کرد، برای دیدن تغییرات برنامه را دوباره راه‌اندازی کنید",
            "accountDetails" to "مشخصات حساب",
            "level" to "سطح",
            "editAccount" to "ویرایش حساب",
            "balance" to "موجودی",
            "aboutApp" to "درباره برنامه",
            "policy" to "سیاست",
            "donate" to "کمک مالی",
            "understood" to "فهمیدم",
            "close" to "بستن",
            "shareAndEarn" to "به اشتراک بگذارید و اجر ببرید",
            "checkUpdates" to "بررسی به‌روزرسانی‌ها",
            "sendSuggestion" to "ارسال پیشنهاد",
            "reportBugTitle" to "گزارش خطا.",
            "writeHere" to "اینجا بنویسید...",
            "submit" to "ارسال",
            "fajr" to "فجر",
            "shuruj" to "طلوع آفتاب",
            "dhuhr" to "ظهر",
            "asr" to "عصر",
            "maghrib" to "مغرب",
            "isha" to "عشا",
            "nextPrayer" to "نماز بعدی",
            "remainingTime" to "زمان باقی‌مانده",
            "locationTitle" to "تعیین موقعیت",
            "locationMessage" to "فقط یک بار به موقعیت شما نیاز داریم تا اوقات نماز را دقیقاً بر اساس شهر شما محاسبه کنیم.",
            "useMyLocation" to "استفاده از موقعیت من",
            "useKhartoum" to "خارطوم (پیش‌فرض)",
            "completedLog" to "سوابق وظایف انجام‌شده",
            "noCompletedTasks" to "هنوز وظیفه‌ای انجام نشده است",
            "hasanatAdded" to "به موجودی شما افزوده شد",
            "blessedWithCount" to "بارک‌الله فیک! شما به دست آوردید",
            "mayAllahAccept" to "خداوند طاعت شما را قبول کند",
            "aboutText" to "بانک حسنات برنامه‌ای اسلامی است که به شما کمک می‌کند وقت خود را در طاعات سرمایه‌گذاری کنید و حسنات جمع کنید: وظایف و اعمال پیشنهادی همراه با اجر و دلیل، محاسبه روزانه نفس، اذکار صبح و شام، تسبیح دیجیتال و اوقات نماز. برنامه را به اشتراک بگذارید و آن را صدقه جاریه در میزان حسنات خود قرار دهید.",
        ),
        "sw" to mapOf(
            "appName" to "Benki ya Hasanat",
            "hasanatSuffix" to "hasanat",
            "loginTitle" to "Ingia",
            "loginSubtitle" to "Hatua isiyo ya lazima unayoweza kuiruka",
            "username" to "Jina la mtumiaji",
            "password" to "Nenosiri",
            "login" to "Ingia",
            "dontShowAgain" to "Usionyeshe tena",
            "skip" to "Ruka",
            "tasks" to "Kazi",
            "business" to "Amali",
            "dailyReview" to "Mapitio ya kila siku",
            "myAccount" to "Akaunti yangu",
            "share" to "Shiriki",
            "salatTimes" to "Nyakati za sala",
            "azkar" to "Adhkar za asubuhi na jioni",
            "sibha" to "Tasbihi",
            "settings" to "Mipangilio",
            "about" to "Kuhusu",
            "language" to "Lugha",
            "exit" to "Toka",
            "suggestedBusiness" to "Amali zilizopendekezwa",
            "investmentDuration" to "Muda",
            "netProfit" to "Thawabu",
            "investmentDetails" to "Maelezo:",
            "confirmCompletion" to "Thibitisha ukamilishaji",
            "useSibha" to "Tumia tasbihi",
            "didYouDoIt" to "Je, umeikamilisha?",
            "confirmHonestly" to "Je, unathibitisha kwa ukweli kwamba umekamilisha kazi iliyotajwa hapa?",
            "yesOfCourse" to "Ndiyo, hakika",
            "noLater" to "Hapana, nitafanya",
            "blessedMsg" to "Mungu akubariki, mafanikio mapya: ",
            "prev" to "Iliyotangulia",
            "next" to "Inayofuata",
            "endOfQuestions" to "Maswali yamekwisha!",
            "startOfQuestions" to "Mwanzo wa maswali!",
            "reset" to "Weka upya",
            "customWird" to "Wirdi maalum",
            "wirdText" to "Maandishi ya wirdi",
            "repeatCount" to "Idadi ya marudio",
            "save" to "Hifadhi",
            "cancel" to "Ghairi",
            "dontLeaveEmpty" to "Usiiache sehemu hii wazi",
            "numbersOnly" to "Weka nambari tu",
            "notifications" to "Arifa",
            "nightTheme" to "Mandhari ya usiku",
            "zikrToasts" to "Vikumbusho vya adhkar",
            "toastTasbih" to "Vikumbusho vya tasbihi na adhkar",
            "toastProphet" to "Swalawat kwa Mtume",
            "toastAll" to "Zote",
            "reportBug" to "Ripoti hitilafu",
            "enabled" to "Imewashwa",
            "disabled" to "Imezimwa",
            "chooseLanguage" to "Chagua lugha ya programu",
            "saveChanges" to "Hifadhi mabadiliko?",
            "restartNeeded" to "Unahitaji kuanzisha upya programu ili uone mabadiliko.",
            "restart" to "Anzisha upya",
            "later" to "Baadaye",
            "langChanged" to "Lugha imebadilishwa kikamilifu, anzisha upya programu ili uone mabadiliko",
            "accountDetails" to "Maelezo ya akaunti",
            "level" to "Kiwango",
            "editAccount" to "Hariri akaunti",
            "balance" to "Salio",
            "aboutApp" to "Kuhusu programu",
            "policy" to "Sera",
            "donate" to "Changia",
            "understood" to "Nimeelewa",
            "close" to "Funga",
            "shareAndEarn" to "Shiriki na upate thawabu",
            "checkUpdates" to "Angalia masasisho",
            "sendSuggestion" to "Tuma pendekezo",
            "reportBugTitle" to "Ripoti hitilafu.",
            "writeHere" to "Andika hapa...",
            "submit" to "Tuma",
            "fajr" to "Alfajiri",
            "shuruj" to "Kuchomoza kwa jua",
            "dhuhr" to "Adhuhuri",
            "asr" to "Alasiri",
            "maghrib" to "Magharibi",
            "isha" to "Isha",
            "nextPrayer" to "Sala inayofuata",
            "remainingTime" to "Muda uliobaki",
            "locationTitle" to "Weka eneo",
            "locationMessage" to "Tunahitaji eneo lako mara moja tu ili kukokotoa nyakati sahihi za sala kwa mji wako.",
            "useMyLocation" to "Tumia eneo langu",
            "useKhartoum" to "Khartoum (chaguo-msingi)",
            "completedLog" to "Rekodi ya kazi zilizokamilika",
            "noCompletedTasks" to "Hakuna kazi zilizokamilika bado",
            "hasanatAdded" to "zimeongezwa kwenye salio lako",
            "blessedWithCount" to "Mungu akubariki! Umepata",
            "mayAllahAccept" to "Mungu aikubali ibada yako",
            "aboutText" to "Benki ya Hasanat ni programu ya Kiislamu inayokusaidia kuwekeza muda wako katika ibada na kukusanya hasanat: kazi na amali zilizopendekezwa zenye thawabu na dalili, mapitio ya kila siku ya nafsi, adhkar za asubuhi na jioni, tasbihi ya kidijitali, na nyakati za sala. Shiriki programu na uifanye sadaka inayoendelea katika mizani ya hasanat zako.",
        ),
        "ha" to mapOf(
            "appName" to "Bankin Hasanat",
            "hasanatSuffix" to "hasanat",
            "loginTitle" to "Shiga",
            "loginSubtitle" to "Mataki ne wanda ba dole ba ne, za ka iya tsallake shi",
            "username" to "Sunan mai amfani",
            "password" to "Kalmar sirri",
            "login" to "Shiga",
            "dontShowAgain" to "Kada a sake nunawa",
            "skip" to "Tsallake",
            "tasks" to "Ayyuka",
            "business" to "Ayyukan alheri",
            "dailyReview" to "Bitar kullum",
            "myAccount" to "Asusuna",
            "share" to "Raba",
            "salatTimes" to "Lokutan salla",
            "azkar" to "Azkar na safe da yamma",
            "sibha" to "Tasbihi",
            "settings" to "Saituna",
            "about" to "Game da",
            "language" to "Harshe",
            "exit" to "Fita",
            "suggestedBusiness" to "Ayyukan da aka ba da shawara",
            "investmentDuration" to "Tsawon lokaci",
            "netProfit" to "Lada",
            "investmentDetails" to "Bayanai:",
            "confirmCompletion" to "Tabbatar da kammalawa",
            "useSibha" to "Yi amfani da tasbihi",
            "didYouDoIt" to "Shin ka kammala aikin?",
            "confirmHonestly" to "Shin da gaskiya ka tabbatar ka kammala aikin da aka ambata a nan?",
            "yesOfCourse" to "I, tabbas",
            "noLater" to "A'a, zan yi",
            "blessedMsg" to "Allah ya albarkace ka, sabon nasara: ",
            "prev" to "Na baya",
            "next" to "Na gaba",
            "endOfQuestions" to "Tambayoyi sun ƙare!",
            "startOfQuestions" to "Farkon tambayoyi!",
            "reset" to "Sake saitawa",
            "customWird" to "Wirdi na musamman",
            "wirdText" to "Rubutun wirdi",
            "repeatCount" to "Yawan maimaitawa",
            "save" to "Ajiye",
            "cancel" to "Soke",
            "dontLeaveEmpty" to "Kada ka bar wannan fili babu komai",
            "numbersOnly" to "Shigar da lambobi kawai",
            "notifications" to "Sanarwa",
            "nightTheme" to "Yanayin dare",
            "zikrToasts" to "Tunatarwa na azkar",
            "toastTasbih" to "Tunatarwa na tasbihi da azkar",
            "toastProphet" to "Salati ga Annabi",
            "toastAll" to "Duka",
            "reportBug" to "Ba da rahoton kuskure",
            "enabled" to "A kunne",
            "disabled" to "A kashe",
            "chooseLanguage" to "Zaɓi harshen manhaja",
            "saveChanges" to "Ajiye canje-canje?",
            "restartNeeded" to "Dole ne ka sake kunna manhajar don ganin canje-canje.",
            "restart" to "Sake kunnawa",
            "later" to "Daga baya",
            "langChanged" to "An canza harshe cikin nasara, sake kunna manhajar don ganin canje-canje",
            "accountDetails" to "Bayanin asusu",
            "level" to "Mataki",
            "editAccount" to "Gyara asusu",
            "balance" to "Ragowa",
            "aboutApp" to "Game da manhaja",
            "policy" to "Manufa",
            "donate" to "Ba da gudummawa",
            "understood" to "Na gane",
            "close" to "Rufe",
            "shareAndEarn" to "Raba ka sami lada",
            "checkUpdates" to "Duba sabbin bayanai",
            "sendSuggestion" to "Aika shawara",
            "reportBugTitle" to "Ba da rahoton kuskure.",
            "writeHere" to "Rubuta a nan...",
            "submit" to "Aika",
            "fajr" to "Asuba",
            "shuruj" to "Fitowar rana",
            "dhuhr" to "Azahar",
            "asr" to "La'asar",
            "maghrib" to "Magariba",
            "isha" to "Isha'i",
            "nextPrayer" to "Salla ta gaba",
            "remainingTime" to "Lokacin da ya rage",
            "locationTitle" to "Zaɓi wuri",
            "locationMessage" to "Muna buƙatar wurin ka sau ɗaya kawai don ƙididdige daidaitattun lokutan salla na birninka.",
            "useMyLocation" to "Yi amfani da wurina",
            "useKhartoum" to "Khartoum (tsoho)",
            "completedLog" to "Rijistar ayyukan da aka kammala",
            "noCompletedTasks" to "Babu ayyukan da aka kammala tukuna",
            "hasanatAdded" to "an ƙara zuwa ragowarka",
            "blessedWithCount" to "Allah ya albarkace ka! Ka samu",
            "mayAllahAccept" to "Allah ya karɓi ibadarka",
            "aboutText" to "Bankin Hasanat manhaja ce ta Musulunci wadda ke taimaka maka ka zuba lokacinka a cikin biyayya ka tara hasanat: ayyuka da aka ba da shawara tare da lada da hujja, bitar kai na kullum, azkar na safe da yamma, tasbihi na zamani, da lokutan salla. Raba manhajar ka sanya ta sadaka mai gudana a ma'aunin hasanat ɗinka.",
        ),
        "bn" to mapOf(
            "appName" to "হাসানাত ব্যাংক",
            "hasanatSuffix" to "হাসানাত",
            "loginTitle" to "লগইন",
            "loginSubtitle" to "একটি অপ্রয়োজনীয় ধাপ যা আপনি এড়িয়ে যেতে পারেন",
            "username" to "ব্যবহারকারীর নাম",
            "password" to "পাসওয়ার্ড",
            "login" to "প্রবেশ",
            "dontShowAgain" to "আর দেখাবেন না",
            "skip" to "এড়িয়ে যান",
            "tasks" to "কাজসমূহ",
            "business" to "আমলসমূহ",
            "dailyReview" to "দৈনিক আত্মসমালোচনা",
            "myAccount" to "আমার অ্যাকাউন্ট",
            "share" to "শেয়ার",
            "salatTimes" to "নামাজের সময়সূচি",
            "azkar" to "সকাল-সন্ধ্যার যিকির",
            "sibha" to "তাসবীহ",
            "settings" to "সেটিংস",
            "about" to "সম্পর্কে",
            "language" to "ভাষা",
            "exit" to "বাহির",
            "suggestedBusiness" to "প্রস্তাবিত আমলসমূহ",
            "investmentDuration" to "মেয়াদ",
            "netProfit" to "সওয়াব",
            "investmentDetails" to "বিস্তারিত:",
            "confirmCompletion" to "সম্পন্ন হওয়ার নিশ্চিতকরণ",
            "useSibha" to "তাসবীহ ব্যবহার করুন",
            "didYouDoIt" to "আপনি কি কাজটি সম্পন্ন করেছেন?",
            "confirmHonestly" to "আপনি কি সততার সাথে নিশ্চিত করছেন যে এখানে উল্লিখিত কাজটি আপনি সম্পন্ন করেছেন?",
            "yesOfCourse" to "হ্যাঁ, অবশ্যই",
            "noLater" to "না, আমি করব",
            "blessedMsg" to "আল্লাহ আপনাকে বরকত দিন, নতুন অর্জন: ",
            "prev" to "পূর্ববর্তী",
            "next" to "পরবর্তী",
            "endOfQuestions" to "প্রশ্ন শেষ!",
            "startOfQuestions" to "প্রশ্নের শুরু!",
            "reset" to "রিসেট",
            "customWird" to "কাস্টম ওযির্দ",
            "wirdText" to "ওযির্দের পাঠ্য",
            "repeatCount" to "পুনরাবৃত্তির সংখ্যা",
            "save" to "সংরক্ষণ",
            "cancel" to "বাতিল",
            "dontLeaveEmpty" to "এই ঘরটি খালি রাখবেন না",
            "numbersOnly" to "শুধু সংখ্যা লিখুন",
            "notifications" to "বিজ্ঞপ্তি",
            "nightTheme" to "নাইট মোড",
            "zikrToasts" to "যিকিরের স্মরণিকা",
            "toastTasbih" to "তাসবীহ ও যিকিরের স্মরণিকা",
            "toastProphet" to "নবীর প্রতি দরূদ",
            "toastAll" to "সব",
            "reportBug" to "ত্রুটি রিপোর্ট করুন",
            "enabled" to "চালু",
            "disabled" to "বন্ধ",
            "chooseLanguage" to "অ্যাপের ভাষা নির্বাচন করুন",
            "saveChanges" to "পরিবর্তন সংরক্ষণ করবেন?",
            "restartNeeded" to "পরিবর্তন দেখতে আপনাকে অ্যাপটি পুনরায় চালু করতে হবে।",
            "restart" to "পুনরায় চালু",
            "later" to "পরে",
            "langChanged" to "ভাষা সফলভাবে পরিবর্তিত হয়েছে, পরিবর্তন দেখতে অ্যাপটি পুনরায় চালু করুন",
            "accountDetails" to "অ্যাকাউন্টের বিবরণ",
            "level" to "স্তর",
            "editAccount" to "অ্যাকাউন্ট সম্পাদনা",
            "balance" to "ব্যালেন্স",
            "aboutApp" to "অ্যাপ সম্পর্কে",
            "policy" to "নীতি",
            "donate" to "দান",
            "understood" to "বুঝেছি",
            "close" to "বন্ধ",
            "shareAndEarn" to "শেয়ার করুন ও সওয়াব অর্জন করুন",
            "checkUpdates" to "আপডেট পরীক্ষা করুন",
            "sendSuggestion" to "পরামর্শ পাঠান",
            "reportBugTitle" to "ত্রুটি রিপোর্ট করুন।",
            "writeHere" to "এখানে লিখুন...",
            "submit" to "পাঠান",
            "fajr" to "ফজর",
            "shuruj" to "সূর্যোদয়",
            "dhuhr" to "যোহর",
            "asr" to "আসর",
            "maghrib" to "মাগরিব",
            "isha" to "ইশা",
            "nextPrayer" to "পরবর্তী নামাজ",
            "remainingTime" to "বাকি সময়",
            "locationTitle" to "অবস্থান নির্ধারণ",
            "locationMessage" to "আপনার শহরের সঠিক নামাজের সময় গণনার জন্য আমাদের শুধুমাত্র একবার আপনার অবস্থান প্রয়োজন।",
            "useMyLocation" to "আমার অবস্থান ব্যবহার করুন",
            "useKhartoum" to "খার্তুম (ডিফল্ট)",
            "completedLog" to "সম্পন্ন কাজের রেকর্ড",
            "noCompletedTasks" to "এখনও কোনো কাজ সম্পন্ন হয়নি",
            "hasanatAdded" to "আপনার ব্যালেন্সে যোগ হয়েছে",
            "blessedWithCount" to "আল্লাহ আপনাকে বরকত দিন! আপনি পেয়েছেন",
            "mayAllahAccept" to "আল্লাহ আপনার ইবাদত কবুল করুন",
            "aboutText" to "হাসানাত ব্যাংক একটি ইসলামিক অ্যাপ যা আপনার সময়কে ইবাদতে বিনিয়োগ করতে ও হাসানাত সংগ্রহ করতে সাহায্য করে: সওয়াব ও প্রমাণসহ প্রস্তাবিত কাজ ও আমল, দৈনিক আত্মসমালোচনা, সকাল-সন্ধ্যার যিকির, ডিজিটাল তাসবীহ এবং নামাজের সময়সূচি। অ্যাপটি শেয়ার করুন এবং এটিকে আপনার হাসানাতের পাল্লায় সদকায়ে জারিয়া বানান।",
        ),
        "tr" to mapOf(
            "appName" to "Hasenat Bankası",
            "hasanatSuffix" to "hasenat",
            "loginTitle" to "Giriş",
            "loginSubtitle" to "Atlayabileceğiniz gereksiz bir adım",
            "username" to "Kullanıcı adı",
            "password" to "Şifre",
            "login" to "Giriş",
            "dontShowAgain" to "Bir daha gösterme",
            "skip" to "Atla",
            "tasks" to "Görevler",
            "business" to "Ameller",
            "dailyReview" to "Günlük muhasebe",
            "myAccount" to "Hesabım",
            "share" to "Paylaş",
            "salatTimes" to "Namaz vakitleri",
            "azkar" to "Sabah ve akşam zikirleri",
            "sibha" to "Tesbih",
            "settings" to "Ayarlar",
            "about" to "Hakkında",
            "language" to "Dil",
            "exit" to "Çıkış",
            "suggestedBusiness" to "Önerilen ameller",
            "investmentDuration" to "Süre",
            "netProfit" to "Sevap",
            "investmentDetails" to "Detaylar:",
            "confirmCompletion" to "Tamamlamayı onayla",
            "useSibha" to "Tesbih kullan",
            "didYouDoIt" to "İşi tamamladınız mı?",
            "confirmHonestly" to "Burada belirtilen görevi tamamladığınızı dürüstçe onaylıyor musunuz?",
            "yesOfCourse" to "Evet, elbette",
            "noLater" to "Hayır, yapacağım",
            "blessedMsg" to "Allah razı olsun, yeni başarı: ",
            "prev" to "Önceki",
            "next" to "Sonraki",
            "endOfQuestions" to "Sorular bitti!",
            "startOfQuestions" to "Soruların başı!",
            "reset" to "Sıfırla",
            "customWird" to "Özel vird",
            "wirdText" to "Vird metni",
            "repeatCount" to "Tekrar sayısı",
            "save" to "Kaydet",
            "cancel" to "İptal",
            "dontLeaveEmpty" to "Bu alanı boş bırakmayın",
            "numbersOnly" to "Yalnızca rakam girin",
            "notifications" to "Bildirimler",
            "nightTheme" to "Gece modu",
            "zikrToasts" to "Zikir hatırlatmaları",
            "toastTasbih" to "Tesbih ve zikir hatırlatmaları",
            "toastProphet" to "Peygamber'e salavat",
            "toastAll" to "Tümü",
            "reportBug" to "Hata bildir",
            "enabled" to "Açık",
            "disabled" to "Kapalı",
            "chooseLanguage" to "Uygulama dilini seçin",
            "saveChanges" to "Değişiklikler kaydedilsin mi?",
            "restartNeeded" to "Değişiklikleri görmek için uygulamayı yeniden başlatmanız gerekir.",
            "restart" to "Yeniden başlat",
            "later" to "Sonra",
            "langChanged" to "Dil başarıyla değiştirildi, değişiklikleri görmek için uygulamayı yeniden başlatın",
            "accountDetails" to "Hesap bilgileri",
            "level" to "Seviye",
            "editAccount" to "Hesabı düzenle",
            "balance" to "Bakiye",
            "aboutApp" to "Uygulama hakkında",
            "policy" to "Politika",
            "donate" to "Bağış",
            "understood" to "Anladım",
            "close" to "Kapat",
            "shareAndEarn" to "Paylaş ve sevap kazan",
            "checkUpdates" to "Güncellemeleri denetle",
            "sendSuggestion" to "Öneri gönder",
            "reportBugTitle" to "Hata bildir.",
            "writeHere" to "Buraya yazın...",
            "submit" to "Gönder",
            "fajr" to "Sabah",
            "shuruj" to "Güneş",
            "dhuhr" to "Öğle",
            "asr" to "İkindi",
            "maghrib" to "Akşam",
            "isha" to "Yatsı",
            "nextPrayer" to "Sonraki namaz",
            "remainingTime" to "Kalan süre",
            "locationTitle" to "Konum belirle",
            "locationMessage" to "Şehrinize göre doğru namaz vakitlerini hesaplamak için konumunuza yalnızca bir kez ihtiyacımız var.",
            "useMyLocation" to "Konumumu kullan",
            "useKhartoum" to "Hartum (varsayılan)",
            "completedLog" to "Tamamlanan görevler kaydı",
            "noCompletedTasks" to "Henüz tamamlanan görev yok",
            "hasanatAdded" to "bakiyenize eklendi",
            "blessedWithCount" to "Allah razı olsun! Kazandınız:",
            "mayAllahAccept" to "Allah ibadetinizi kabul etsin",
            "aboutText" to "Hasenat Bankası, vaktinizi ibadete yatırmanıza ve hasenat toplamanıza yardımcı olan İslami bir uygulamadır: sevap ve delilleriyle önerilen görev ve ameller, günlük nefis muhasebesi, sabah ve akşam zikirleri, dijital tesbih ve namaz vakitleri. Uygulamayı paylaşın ve hasenat terazinize sadaka-i cariye olarak ekleyin.",
        ),
    )

    fun get(lang: String, key: String): String? = table[lang]?.get(key)
}
